# Generated by Django 5.1.7 on 2025-04-05 08:59

from os import getenv
from typing import TYPE_CHECKING, cast
from django.db import migrations


def create_superuser(apps, schema_editor):
    User = cast("UserModel", apps.get_model("user", "User"))
    User.objects.create_superuser(
        username=getenv("DJANGO_ADMIN_USERNAME", "admin"),
        password=getenv("DJANGO_ADMIN_PASSWORD", "admin"),
        email=getenv("DJANGO_ADMIN_EMAIL", "admin@admin.com"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
